### ISSUE TITLE
💡 [REQUEST] - Scope parameter is not supported on an authorization code access_token exchange request

### ISSUE THREAD

**Issue by a-besson** [soofstad/react-oauth2-pkce#129]
### Summary

Hi,

First many thanks for this package who helped us to implement oauth2 pkce easly on our enterprise project :-) 

During our implementation we've got an issue with the token request:

```
{
  "error_description": "Scope parameter is not supported on an authorization code access_token exchange request. Scope parameter should be supplied to the authorize request.",
  "error": "invalid_request"
}
```

Apparently on our enterprise IAM, providing scope to a token is not accepted.

We had to fork and modify this line to get it work : https://github.com/soofstad/react-oauth2-pkce/blob/main/src/authentication.ts#L84.

Would that be possible de make this parameter optionnal for token request ?  Can we contribute :-) ? 

Thanks
Adrien BESSON

### Basic Example

Oauth2 error on token request: Scope parameter is not supported on an authorization code access_token exchange request

### Drawbacks

no impacts if parameter is made optionnal

**Comment by anthony-vito** [comment]
The "scope" should not be sent with the token request at all, it is not in the spec and should never be needed by an IDP. It should be removed.

The specification calls out (5) parameters that should be sent with the token request for PKCE flow.

- code_verifier
- code
- grant_type
- redirect_uri
- client_id

Technically this is a bug. I'll make a pull request.

**Comment by soofstad** [comment]
Thanks for reporting @a-besson :slightly_smiling_face: 

And you are absolutely right @anthony-vito, it should never have been there in the first place.

Out of curiosity, which Auth provider were you using besson? Usually they will silently ignore any extra parameters they don't need.

**Comment by romaindequidt** [comment]
HI, I'm the colleague of @a-besson . 
PKCE is enabled through this setting: com.forgerock.tosiam.oauth2provider.code-verifier-enforced=true
So, I think the Auth provider is rather a Forgerock IAM product (but an old one, 2015) than keycloack.

**Comment by anfreita** [comment]
Hi, thanks for all the great work you all are doing!

Not sure if a +1 is helpful at this point since the PR is already up, but I'll add that I'm getting this error from the Salesforce provider token endpoint:
```
{"error":"invalid_request","error_description":"scope parameter not supported"}
```

**Comment by soofstad** [comment]
A fix is available in v1.15.3 :tada: 
Thanks to @anthony-vito for the PR, and to all of you reporting the issue.

**Comment by anfreita** [comment]
Thanks for addressing this so quickly!

I'm still seeing this error since the `scope` parameter is being added to the refresh request. I see in the spec that this is an optional parameter (required when `grant_type=password`), and the `TTokenRequestForRefresh` type reflects that, however the request includes it by default, and the ID provider we're using (Salesforce) returns an error if it is included. Would it be possible to exclude the parameter by default and add a config option or utilize the `extraTokenParameters` option? I'm happy to send a PR, please let me know.

**Comment by soofstad** [comment]
Alright, thanks for testing.
I guess there is no other option than to make this configurable with an "opt-out".
I've made a PR here that should resolve it: https://github.com/soofstad/react-oauth2-pkce/pull/132
